INSERT INTO Procedure_Types SELECT 'Arthroplasty of knee', 'A1'
INSERT INTO Procedure_Types SELECT 'Appendectomy', 'A2'
INSERT INTO Procedure_Types SELECT 'Cesarean section', 'C1'
INSERT INTO Procedure_Types SELECT 'Colorectal resection', 'C2'
INSERT INTO Procedure_Types SELECT 'Coronary artery bypass graft', 'C3'
INSERT INTO Procedure_Types SELECT 'Heart valve procedures', 'H1'
INSERT INTO Procedure_Types SELECT 'Hip replacement, total and partial', 'H2'
INSERT INTO Procedure_Types SELECT 'Amputation of lower extremity', 'A3'
INSERT INTO Procedure_Types SELECT 'Spinal fusion', 'S1'
INSERT INTO Procedure_Types SELECT 'Tonsillectomy', 'T1'
